#!/usr/bin/env python3
"""
Credential Loader: /opt/ai-brain/.credentials/tokens.md → .env

tokens.md のセクションを解析して .env を生成し、
/root/.profile を上書き更新する。

使い方:
  python3 cred-loader.py                  # .env のみ更新
  python3 cred-loader.py --update-profile # .env + /root/.profile を更新
  python3 cred-loader.py --check          # 登録済みキー一覧を表示
"""
import re, sys
from pathlib import Path

CRED_DIR  = Path("/opt/ai-brain/.credentials")
TOKENS_MD = CRED_DIR / "tokens.md"
ENV_FILE  = CRED_DIR / ".env"
PROFILE   = Path("/root/.profile")

# tokens.md セクション名 + キー名 → 環境変数名
KEY_MAP: dict[str, dict[str, str]] = {
    "GITHUB":    {"PAT": "GITHUB_TOKEN"},
    "DISCORD":   {"WEBHOOK_URL": "DISCORD_WEBHOOK_URL"},
    "CONOHA":    {
        "USERNAME":  "CONOHA_USERNAME",
        "PASSWORD":  "CONOHA_PASSWORD",
        "TENANT_ID": "CONOHA_TENANT_ID",
        "REGION":    "CONOHA_REGION",
    },
    "ANTHROPIC": {"API_KEY": "ANTHROPIC_API_KEY"},
    "NOTION":    {"TOKEN": "NOTION_TOKEN"},
    "YOUTUBE":   {"API_KEY": "YOUTUBE_API_KEY", "CHANNEL_ID": "YOUTUBE_CHANNEL_ID"},
}

_PLACEHOLDER = {"", "YOUR_VALUE_HERE", "xxx", "---", "your_value_here"}


def parse_tokens_md(path: Path) -> dict[str, str]:
    if not path.exists():
        print(f"❌ tokens.md が見つかりません: {path}", file=sys.stderr)
        sys.exit(1)

    env: dict[str, str] = {}
    section: str | None = None

    for line in path.read_text().splitlines():
        m = re.match(r"^##\s+(\w+)\s*$", line)
        if m:
            section = m.group(1).upper()
            continue

        m = re.match(r"^(\w+):\s*(.+)$", line)
        if m and section:
            key = m.group(1).upper()
            val = m.group(2).strip()
            if val in _PLACEHOLDER:
                continue
            env_key = KEY_MAP.get(section, {}).get(key, f"{section}_{key}")
            env[env_key] = val

    return env


def write_env(env: dict[str, str], path: Path) -> None:
    """systemd EnvironmentFile 形式 (KEY=value, export なし) で書き出す"""
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    lines = ["# Auto-generated by cred-loader.py — do not edit manually\n"]
    for k in sorted(env):
        lines.append(f'{k}="{env[k]}"\n')
    path.write_text("".join(lines))
    path.chmod(0o600)


def update_profile(env: dict[str, str], profile: Path) -> None:
    """bash の .profile / .bashrc 向け (export KEY="value" 形式) で更新"""
    text = profile.read_text() if profile.exists() else ""
    for k, v in env.items():
        pattern = re.compile(
            rf'^(?:export\s+)?{re.escape(k)}=.*$', re.MULTILINE
        )
        new_line = f'export {k}="{v}"'
        if pattern.search(text):
            text = pattern.sub(new_line, text)
        else:
            text = text.rstrip("\n") + f"\n{new_line}\n"
    profile.write_text(text)


def main() -> None:
    args = sys.argv[1:]

    if "--check" in args:
        env = parse_tokens_md(TOKENS_MD)
        print(f"tokens.md から {len(env)} 件のキーを読み込み済み:")
        for k in sorted(env):
            print(f"  {k}")
        return

    env = parse_tokens_md(TOKENS_MD)
    if not env:
        print("⚠️  tokens.md に有効な認証情報がありません", file=sys.stderr)
        sys.exit(1)

    write_env(env, ENV_FILE)
    print(f"✅ .env 更新完了 ({len(env)} 件): {ENV_FILE}")

    if "--update-profile" in args:
        update_profile(env, PROFILE)
        print(f"✅ {PROFILE} 更新完了")


if __name__ == "__main__":
    main()
